"""add squad and premier league tables from models

Revision ID: ee619c89fb3b
Revises: 
Create Date: 2023-07-03 21:47:55.351924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ee619c89fb3b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create schema squad")
    op.execute("create schema premier_league")

    op.create_table(
        "place",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("place", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_place")),
        sa.UniqueConstraint("id", name=op.f("uq_place_id")),
        sa.UniqueConstraint("place", name=op.f("uq_place_place")),
        schema="premier_league",
    )
    op.create_table(
        "result",
        sa.Column("id_result", sa.Integer(), nullable=False),
        sa.Column("result", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id_result", name=op.f("pk_result")),
        sa.UniqueConstraint("id_result", name=op.f("uq_result_id_result")),
        sa.UniqueConstraint("result", name=op.f("uq_result_result")),
        schema="premier_league",
    )
    op.create_table(
        "team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team")),
        sa.UniqueConstraint("id", name=op.f("uq_team_id")),
        sa.UniqueConstraint("team", name=op.f("uq_team_team")),
        schema="premier_league",
    )
    op.create_table(
        "country",
        sa.Column("id_country", sa.Integer(), nullable=False),
        sa.Column("country", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id_country", name=op.f("pk_country")),
        sa.UniqueConstraint("country", name=op.f("uq_country_country")),
        sa.UniqueConstraint("id_country", name=op.f("uq_country_id_country")),
        schema="squad",
    )
    op.create_table(
        "position",
        sa.Column("id_position", sa.Integer(), nullable=False),
        sa.Column("position", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id_position", name=op.f("pk_position")),
        sa.UniqueConstraint("id_position", name=op.f("uq_position_id_position")),
        sa.UniqueConstraint("position", name=op.f("uq_position_position")),
        schema="squad",
    )
    op.create_table(
        "match",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_date", sa.Date(), nullable=False),
        sa.Column("opponent", sa.Text(), nullable=False),
        sa.Column("place", sa.Text(), nullable=False),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("score_whu", sa.Integer(), nullable=False),
        sa.Column("score_opponent", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["opponent"],
            ["premier_league.team.team"],
            name=op.f("fk_match_opponent_team"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["place"],
            ["premier_league.place.place"],
            name=op.f("fk_match_place_place"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["result"],
            ["premier_league.result.result"],
            name=op.f("fk_match_result_result"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match")),
        sa.UniqueConstraint("game_date", name=op.f("uq_match_game_date")),
        sa.UniqueConstraint("id", name=op.f("uq_match_id")),
        schema="premier_league",
    )
    op.create_table(
        "player",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.Text(), nullable=True),
        sa.Column("last_name", sa.Text(), nullable=False),
        sa.Column("born", sa.Date(), nullable=False),
        sa.Column("country", sa.Text(), nullable=False),
        sa.Column("position", sa.Text(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["country"],
            ["squad.country.country"],
            name=op.f("fk_player_country_country"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["position"],
            ["squad.position.position"],
            name=op.f("fk_player_position_position"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("number", name=op.f("pk_player")),
        sa.UniqueConstraint("number", name=op.f("uq_player_number")),
        schema="squad",
    )
    op.create_table(
        "assist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id_match", sa.Integer(), nullable=True),
        sa.Column("id_player", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_match"],
            ["premier_league.match.id"],
            name=op.f("fk_assist_id_match_match"),
        ),
        sa.ForeignKeyConstraint(
            ["id_player"],
            ["squad.player.number"],
            name=op.f("fk_assist_id_player_player"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assist")),
        sa.UniqueConstraint("id", name=op.f("uq_assist_id")),
        schema="premier_league",
    )
    op.create_table(
        "goal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id_match", sa.Integer(), nullable=True),
        sa.Column("id_player", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_match"],
            ["premier_league.match.id"],
            name=op.f("fk_goal_id_match_match"),
        ),
        sa.ForeignKeyConstraint(
            ["id_player"],
            ["squad.player.number"],
            name=op.f("fk_goal_id_player_player"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goal")),
        sa.UniqueConstraint("id", name=op.f("uq_goal_id")),
        schema="premier_league",
    )
    op.create_table(
        "player_match",
        sa.Column("player_number", sa.Integer(), nullable=True),
        sa.Column("match_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["premier_league.match.id"],
            name=op.f("fk_player_match_match_id_match"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_number"],
            ["squad.player.number"],
            name=op.f("fk_player_match_player_number_player"),
            ondelete="CASCADE",
        ),
        schema="premier_league",
    )
    op.create_table(
        "red_card",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id_match", sa.Integer(), nullable=True),
        sa.Column("id_player", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_match"],
            ["premier_league.match.id"],
            name=op.f("fk_red_card_id_match_match"),
        ),
        sa.ForeignKeyConstraint(
            ["id_player"],
            ["squad.player.number"],
            name=op.f("fk_red_card_id_player_player"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_red_card")),
        sa.UniqueConstraint("id", name=op.f("uq_red_card_id")),
        schema="premier_league",
    )
    op.create_table(
        "yellow_card",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id_match", sa.Integer(), nullable=True),
        sa.Column("id_player", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_match"],
            ["premier_league.match.id"],
            name=op.f("fk_yellow_card_id_match_match"),
        ),
        sa.ForeignKeyConstraint(
            ["id_player"],
            ["squad.player.number"],
            name=op.f("fk_yellow_card_id_player_player"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_yellow_card")),
        sa.UniqueConstraint("id", name=op.f("uq_yellow_card_id")),
        schema="premier_league",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("drop schema squad")
    op.execute("drop schema premier_league")

    op.drop_table("yellow_card", schema="premier_league")
    op.drop_table("red_card", schema="premier_league")
    op.drop_table("player_match", schema="premier_league")
    op.drop_table("goal", schema="premier_league")
    op.drop_table("assist", schema="premier_league")
    op.drop_table("player", schema="squad")
    op.drop_table("match", schema="premier_league")
    op.drop_table("position", schema="squad")
    op.drop_table("country", schema="squad")
    op.drop_table("team", schema="premier_league")
    op.drop_table("result", schema="premier_league")
    op.drop_table("place", schema="premier_league")
    # ### end Alembic commands ###
